from taskcontrol.actions import Queues

config = {"name": "test", "maxsize": 10,
          "queue_type": "queue", "queue": None}
queue = Queues()
q = queue.new(config)
config["queue"] = q
# print(config)
c = queue.create(config)
print(c, queue.validate_add)
print(queue.add("test", "test1"))
print(queue.add("test", "test2"))
print(queue.add("test", "test3"))
print(queue.add("test", "test4"))
print(queue.add("test", "test5"))
print(queue.add("test", "test6"))
print(queue.add("test", "test7"))
print(queue.add("test", "test8"))
print(queue.add("test", "test9"))
print(queue.add("test", "test10"))
print(queue.add("test", "test11"))
print(queue.add("test", "test10"))
print(queue.get("test"))
print(queue.get("test"))
print(queue.get("test"))
print(queue.get("test"))
print(queue.get("test"))
print(queue.get("test"))
print(queue.get("test"))
print(queue.get("test"))
print(queue.get("test"))
print(queue.get("test"))
print(queue.get("test"))
print(queue.get("test"))
