from taskcontrol.lib import TimerBase

timer = TimerBase()

if timer:
    pass

t = timer.timer_create({"name": "testtimer"})
print(t)
if t:
    print("start", timer.start("testtimer"))
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("elapsed_time", timer.elapsed_time("testtimer"))
    print("curent_elapsed_time", timer.curent_elapsed_time("testtimer"))
    print("stop", timer.stop("testtimer"))
    print("elapsed_time", timer.elapsed_time("testtimer"))
    print("curent_elapsed_time", timer.curent_elapsed_time("testtimer"))
    print("start", timer.start("testtimer"))
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("Test")
    print("elapsed_time", timer.elapsed_time("testtimer"))
    print("curent_elapsed_time", timer.curent_elapsed_time("testtimer"))
    print("stop", timer.stop("testtimer"))
    print("elapsed_time", timer.elapsed_time("testtimer"))
    print("curent_elapsed_time", timer.curent_elapsed_time("testtimer"))
    print("reset", timer.reset("testtimer"))
    print("elapsed_time", timer.elapsed_time("testtimer"))
    print("curent_elapsed_time", timer.curent_elapsed_time("testtimer"))
